export const KNOWLEDGE_BASE = [
  {
    "name": "bot-features.md",
    "content": "# Bot Features\n\n## Ask Channel\nUsers can ask questions in the designated channel, and the bot will use AI to answer them based on this documentation.\n\n## Commands\n- Prefix: defined in config (default `!`)\n- Slice command support\n",
    "keywords": [
      "bot",
      "features"
    ]
  },
  {
    "name": "controls.md",
    "content": "# Controls & Keybinds\n\n## Combat & Movement\n- **VAFs (Slow-Mo)**: `G` (Replacer for VATS).\n- **Criticals**: `Z` (While in VAFs).\n- **Leaning**: `Q` and `E` (Uneducated Shooter - note: usually needs to be enabled in MO2/MCM *after* leaving the vault).\n- **Grenades/Explosives**: Hold `Left Alt` (The bash key).\n- **Bash**: Tap `Left Alt`.\n- **Jump**: `Spacebar`. (If it doesn't work on startup, ensure no controllers are plugged in or check keybinds in the ESC menu).\n\n## Utilities & UI\n- **Radial Menu**: `H`. Used for quick access to meds, cigarettes, etc.\n- **Wipe Gas Mask**: `Shift + K`. Use this to clear blood or rain from your visor.\n- **Night Vision (NVG)**: `Shift + U`.\n- **Toggle HUD/Widgets**: `F2` (Immersive HUD).\n- **MODExplorer**: `\\` (Backslash).\n- **Armor Plates**: `Y` (Replace armor plate).\n- **ENB Menu**: `End` or `Delete`.\n- **Dodge**: `N` (Enhanced Movement).\n- **Workshop**: `Home`.\n\n## MCM Settings\n- Most mod-specific controls can be remapped in the **MCM (Mod Configuration Menu)** under the respective mod names (e.g., VAFs, Enhanced Movement, Gas Masks of the Wasteland).\n",
    "keywords": [
      "controls"
    ]
  },
  {
    "name": "gameplay-faq.md",
    "content": "# Gameplay FAQ\n\n## How does the healing system work?\nAnomaly uses a complex health and injury system.\n- **IFAK**: Stops heavy bleed, removes crippled status, heals 1%/s (80s).\n- **SP-1 Stimpak**: Gradual HP/AP regen, cures injuries.\n- **SP-2 Stimpak**: 3%/s HP/Limb healing for 40s. **Requires weapon holstered.**\n- **SAM Splint**: Sets crippled limbs to 1HP.\n- **Note**: Sleeping does not automatically heal crippled parts in this modpack.\n\n## How do I save my game?\nStandard saving is restricted. To save:\n- **Sleep**: at least 1 hour in a bed/couch.\n- **Smoke**: Smoking a cigarette will save your game. \n  - **Tip**: Holster your weapon and use the cigarette from the **Radial Menu (H)** for the animation to play correctly.\n- **Vault 111**: The first safe save spot is the chair by the security baton in the vault.\n\n## How does the Radiation system work?\n- Radiation is highly lethal, especially during storms.\n- **Dual-Layered System**: \n    - **RAD (Tissue Damage)**: Environmental exposure that reduces max HP.\n    - **IRA (Ingested Particles)**: From food, water, and weather. High IRA makes you more vulnerable to RADs.\n- **Medicine**:\n    - **Ca-DTPA Injector**: Replaces Radaway. Removes Rads and IRA. (No sprinting while active).\n    - **Potassium Iodide**: Replaces Rad-X. +200 Rad resist.\n    - **Cleansing Tonic**: Cures **Radiation Poisoning**.\n    - **Alcohol**: Effectively lowers IRA levels.\n\n## Butchering and Hunting\n- To butcher animals for meat and hide, you need a **Knife** or **Blowtorch** in your inventory.\n\n## Is there a Recommended Difficulty?\n- The modpack is designed around **Survival** difficulty.\n\n## Faction Training\n- **Power Armor**: You cannot use Power Armor immediately. You must be trained by a faction that uses it (e.g., Brotherhood of Steel) through their questline.\n",
    "keywords": [
      "gameplay",
      "faq"
    ]
  },
  {
    "name": "general-faq.md",
    "content": "\n## Official Resources\n- **Website & Guide**: [Fallout Anomaly Official Site](https://fallout-anomaly.github.io/websitedev/index.html)\n- **Character Builder**: [Interactive Planner](https://fallout-anomaly.github.io/websitedev/pages/guide.html#ai-assistant)\n- **YouTube Channel**: [Fallout Anomaly](https://www.youtube.com/@FalloutAnomaly)\n\n## Common Questions\n### Where can I find the build generator?\nWe have an interactive build generator on our website: [Character Builder](https://fallout-anomaly.github.io/websitedev/pages/guide.html#ai-assistant)\n\n### How do I report a player?\nUse the slash command `/report @User Reason`. This will alert the staff team privately.\n\n\n### Is there a new game plus?\nNo, Anomaly is designed as a fresh hardcore experience.\n\n### Can I add my own mods?\n**Not recommended**. Adding mods voids support in the Discord. If you must, ensure they are compatible with the existing complex systems (MAIM, SCOURGE, etc.).\n\n### My game is crashing on startup!\n- Check if you have the **Fallout 4 Next-Gen Update** on Steam (required).\n- Ensure your **Page File** is set to at least 20GB.\n- If using an **External Drive**, move the installation to an internal SSD.\n- Verify you don't have \"Weapon Debris\" enabled in the launcher settings (NVIDIA crash).\n\n### I'm stuck in the Vault elevator!\nThis is often a high FPS physics bug. Cap your FPS to 60 or use the `Load Accelerator` settings included.\n\n### Why do I have black face bug?\n- Did you load a save from a different modlist?\n- Did you modify the load order?\n- Try creating a new character to verify.\n\n### How do I use the flashlight?\n- Hold `Tab` (Pip-Boy key) to toggle the flashlight.\n- Some helmets have built-in headlamps.\n",
    "keywords": [
      "general",
      "faq"
    ]
  },
  {
    "name": "install-faq.md",
    "content": "# Wabbajack & Installation FAQ\n\n## Critical Prerequisites\n- **Steam Version Only**: Only the Steam version of Fallout 4 is supported. Update to the latest \"Next-Gen\" version (1.10.980); Wabbajack will handle the downgrade to 1.10.163 automatically.\n- **Visual C++ & .NET**: Ensure you have installed [Microsoft Visual C++ AIO](https://github.com/abbodi1406/vcredist/releases) and [.NET Framework 4.6.2 & 5.0](https://dotnet.microsoft.com/en-us/download/dotnet-framework).\n- **Page File**: Configure at least a **16GB Page File** on your SSD to prevent out-of-memory crashes.\n- **Launch Vanilla Once**: You must launch the vanilla game once through Steam to set registry keys before using Wabbajack.\n\n## Common Download & Install Errors\n- **Antivirus Interference**: Add a folder exclusion for your entire Fallout Anomaly installation folder to prevent AV from deleting critical DLLs.\n- **Disable Overlays**: Steam, Discord, Medal, and OBS overlays cause immediate crashes. Disable them before launching.\n- **ENB Download Fail**: If Wabbajack fails to download the ENB, download it manually from [enbdev.com](http://enbdev.com/mod_fallout4_v0501.htm) and place the zip (DO NOT EXTRACT) into your Wabbajack **Downloads** folder.\n- **False Positive: \"Fallout 76\" Error**: Safe to ignore.\n\n## Installation Best Practices\n- **Internal SSD Required**: 350GB of SSD space is required. External drives cause extreme stuttering and crashes.\n- **Updating**: To update, run Wabbajack and point it to your existing folders. It will only download the updated files (Delta update).\n\n## Technical Initial Setup\n- **MCM Initialization**: The first launch involves dozens of scripts firing. Your game will likely freeze for 1-2 minutes when you first open the MCM or pick up the Pip-Boy. **Be patient.**\n- **Post-Character Freeze**: The game may appear to freeze after you finish creating your character. This is normal script initialization; wait it out.\n",
    "keywords": [
      "install",
      "faq"
    ]
  },
  {
    "name": "perks-traits.md",
    "content": "\n## Perks & Skills Setup\nThis modpack uses **\"You Are Exceptional\"** by `Augoeides`.\n- **Mod Link**: [You Are Exceptional on Nexus](https://www.nexusmods.com/fallout4/mods/76739)\n\n### Key Features\n- **Return of Skills**: Reintroduces 13 classic skills (Guns, Energy Weapons, Medicine, Lockpick, Science, Sneak, etc.).\n- **Initial Setup**: At the start (in the Vault elevators or shortly after), you are given a \"You Are Exceptional\" item/menu to allocate starting Points.\n- **Leveling**: You earn **10-15 Skill Points** per level (based on Intelligence) to invest in skills. \n- **Perk Trees**: Perks are now unlocked by **Skill Level** (e.g., Guns 50) rather than just SPECIAL stats.\n\n### Traits System\nYou can choose up to **2 Traits** at character creation. Traits grant unique bonuses but always have a penalty.\n- **Built to Destroy**: +3% Critical Hit Chance, but weapons decay 15% faster.\n- **Fast Shot**: Fire rate increased by 20%, but accuracy decreased by 20%.\n- **Four Eyes**: +2 Perception when wearing glasses, -1 Perception without them.\n- **Good Natured**: +5 to Speech, Medicine, Barter, but -5 to Combat Skills.\n- **Heavy Handed**: Melee/Unarmed do more damage, but critical hits do less damage.\n- **Trigger Discipline**: +20% Accuracy, but -20% Fire Rate.\n- **Wild Wasteland**: Adds humorous and pop-culture references to the world.\n\n### FAQ\n**Q: How do I open the menu?**\nA: Use the **\"You Are Exceptional\"** holotape in your inventory or look for the hotkey bind (often `K` or configurable in MCM).\n\n**Q: Why can't I pick a perk?**\nA: Check if you meet the **Skill Requirement** (e.g., Medicine 75), not just the Level requirement.\n",
    "keywords": [
      "perks",
      "traits"
    ]
  },
  {
    "name": "systems-info.md",
    "content": "# System Information\n\n## Condition Boy (ADAMANT)\nThe widget on your screen shows your current physical state:\n- **Limb Integrity**: Shows health for each limb.\n- **Helmet Status**: The helmet icon indicates if your head is protected. If the icon isn't right, a single headshot may be instant death.\n- **Armor Plates**: High-tier plates (L3 and above) can stop rifle rounds like 5.56. Plates have their own health and will degrade as they take hits.\n\n## Engineering & Schematics\n- **Blueprints**: You need to craft blueprints at the **Engineering Bench**.\n- **Resources**: Crafting journals and blueprints require **Overdue Books** as a primary resource.\n- **Ammo Bench**: Requires specific schematics to craft different calibers.\n\n## Loot & Calibers\n- **True Damage**: Weapon damage is often tied to the caliber rather than a generic \"damage\" stat. \n- **Ammo Variants**: Many calibers have multiple variants (Armor Piercing, Incendiary, etc.). Check the descriptions for their effects.\n- **Enemies**: Enemies use the same armor plate and caliber systems you do.\n\n## You Are Exceptional (YAE)\n- **Reworked System**: Replaces the vanilla perk/SPECIAL system with 26 Skills.\n- **Tagged Skills**: Choose 3 skills for a +25 startup bonus.\n- **Skills vs Perks**: Perks are unlocked by reaching specific Skill levels (e.g., 50 Medicine).\n- **Backgrounds**: Choose a character background at the start for specific gear and skill bonuses.\n\n## Combat Overhaul\n- **True Damage**: Reduces generic NPC weapon damage by 90% and replaces it with logic-based caliber scaling.\n- **SCOURGE**: Adds randomized, non-linear health and resistance stats to all NPCs to make encounters unpredictable.\n- **Munitions**: An expanded ammo framework adding lore-friendly calibers to the Commonwealth.\n\n## VAFs (Vault-Tec Accelerated Focus System)\n- Replaces the standard VATS with a slow-motion \"Bullet Time\" system.\n- Perks that previously affected VATS (like Critical Banker) are integrated into the VAFs system.\n\n## Loot & Scarcity (Damn Apocalypse)\n- **Damn Apocalypse**: A major overhaul that makes the wasteland truly desolate.\n    - **Loot Logic**: Loot is much rarer and more logical.\n    - **Broken Items**: Many items you find may be broken, requiring repair or salvage.\n\n## Hunting & Survival (HOTC)\n- **Hunter of the Commonwealth**: Overhauls animal harvesting.\n    - **Examine Prey**: Use `K` to examine downed animals.\n    - **Harvesting**: Requires a knife or blowtorch.\n",
    "keywords": [
      "systems",
      "info"
    ]
  },
  {
    "name": "troubleshooting.md",
    "content": "# Troubleshooting\n\n## Initial Startup Issues\n- **MCM/Pip-Boy Freeze**: When you first pick up your Pip-Boy or open the MCM in the vault, the game may freeze or take a long time to respond. This is normal; dozens of scripts are firing off at once. Wait a minute or two for them to finish.\n- **Missing Jump/Buttons**: If your controls aren't working right after starting, try restarting the game. Some scripts only finish loading after you exit Vault 111.\n\n## Visual & Performance\n- **Stuttering**: If you have high FPS but see stuttering, it may be a VRAM bottleneck. \n- **Wabbajack Errors**: Most \"Fallout 76\" or \"meshes.ba2\" errors are false positives or temporary metadata issues. Refer to `install-faq.md` for the full fix.\n- **External Drives**: Ensure your game is installed on an internal SSD to avoid major performance hits.\n- **MCM/Pip-Boy Freeze**: When you first pick up your Pip-Boy or open the MCM in the vault, the game may freeze for 1-2 minutes. This is normal script initialization.\n- **Post-Character Freeze**: The game will save and freeze for a few minutes after character creation. **Wait and do not force close the game.**\n\n## Visual & Display Fixes\n- **Screen in Upper Left / Boxed Display**:\n    1. **Disable Overlays**: Disable Discord, Steam, Medal, etc.\n    2. **BethINI**: Close MO2. Run `BethINI.exe` as admin. Set correct resolution and click Save.\n    3. **INI Check**: In MO2, ensure `Fallout4Prefs.ini` has either `bFullscreen=1` or `bBorderless=1`, but not both.\n    4. **DPI Override**: Right-click `Fallout4.exe` in your **Stock Folder** -> Properties -> Compatibility -> Change High DPI settings -> Check \"High DPI Scaling Override\" -> Set to **Application**.\n\n## Common Bugs & Fixes\n- **Falling Through Vault Floor**: This is caused by the \"Uneducated Shooter\" mod. **Only enable this mod after you leave the vault.**\n- **Stuck in Main Menu**: Often caused by slow script loads. Wait at least 5 minutes. If it persists, use one of the pre-made save files provided in the Discord.\n- **Naked Raiders**: This is a known issue with the Merc Veteran armor. Eizer's Robco patches help minimize this.\n- **Stuck in Animation**: Use the console command `PushActorAway player 1` to break locks.\n\n## Bug Reports\n- Use the official bug report form: [Fallout Anomaly Bug Reports](https://falloutanomaly.fillout.com/bugreports)\n",
    "keywords": [
      "troubleshooting"
    ]
  }
];
